spring.application.name=ServiceRegistry

server.port=8761

eureka.instance.hostname=localhost


# Disable Eureka client behavior in the server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

