spring.application.name=HOTEL-SERVICE
server.port:8882

spring.config.import=configserver:http://localhost:8885
spring.datasource.url=jdbc:postgresql://localhost:5432/hotelmicroservice
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


## Enable registration to Eureka server
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## Instance configuration
#eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=true
#
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/